version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false       
      - ES_JAVA_OPTS=-Xms1g -Xmx1g          
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  backend:
    build: .
    container_name: backend
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"
    networks:
      - elk-network


volumes:
  esdata:

networks:
  elk-network:
    driver: bridge
